name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Precompile all gh extension architectures
        uses: cli/gh-extension-precompile@v1
        with:
          go_version: "1.21"
